import { describe, it, expect } from "vitest";
import { generateAgentsMd } from "../agents-md";
import { skillItem, codexOnlyItem, bookmarkItem } from "./fixtures";

describe("generateAgentsMd", () => {
  it("returns header with attribution", () => {
    const result = generateAgentsMd([]);
    expect(result).toContain("# AGENTS.md");
    expect(result).toContain("Generated by Tool Bag");
    expect(result).toContain("https://toolbag-sigma.vercel.app");
  });

  it("groups items by category", () => {
    const result = generateAgentsMd([skillItem, codexOnlyItem]);
    expect(result).toContain("## Skills & Plugins");
    expect(result).toContain("## Testing & QA");
  });

  it("includes item name and description", () => {
    const result = generateAgentsMd([codexOnlyItem]);
    expect(result).toContain("### Codex Tool");
    expect(result).toContain("A Codex-only testing tool.");
  });

  it("includes install command for items with codex_install", () => {
    const result = generateAgentsMd([codexOnlyItem]);
    expect(result).toContain("**Install:**");
    expect(result).toContain("codex install codex-tool");
  });

  it("includes install for items with both platforms", () => {
    const result = generateAgentsMd([skillItem]);
    expect(result).toContain("**Install:**");
    expect(result).toContain("codex install example/claude-debugs");
  });

  it("skips install for Bookmark items", () => {
    const result = generateAgentsMd([bookmarkItem]);
    expect(result).not.toContain("**Install:**");
    expect(result).toContain("### Awesome Claude Code");
  });

  it("includes documentation link", () => {
    const result = generateAgentsMd([codexOnlyItem]);
    expect(result).toContain(
      "- [Documentation](https://example.com/codex-tool)"
    );
  });
});
