import { describe, it, expect } from "vitest";
import { generateAgentsMd } from "../agents-md";
import { skillItem, codexOnlyItem, bookmarkItem } from "./fixtures";

describe("generateAgentsMd", () => {
  it("returns header with attribution", () => {
    const result = generateAgentsMd([]);
    expect(result).toContain("# AGENTS.md");
    expect(result).toContain("Generated by Tool Bag");
    expect(result).toContain("https://toolbag-sigma.vercel.app");
  });

  it("groups items by category", () => {
    const result = generateAgentsMd([skillItem, codexOnlyItem]);
    expect(result).toContain("## Skills & Plugins");
    expect(result).toContain("## Testing & QA");
  });

  it("includes item name and description", () => {
    const result = generateAgentsMd([codexOnlyItem]);
    expect(result).toContain("### Codex Tool");
    expect(result).toContain("A Codex-only testing tool.");
  });

  it("includes install command for items with codex_install", () => {
    const result = generateAgentsMd([codexOnlyItem]);
    expect(result).toContain("**Install:**");
    expect(result).toContain("codex install codex-tool");
  });

  it("includes install for items with both platforms", () => {
    const result = generateAgentsMd([skillItem]);
    expect(result).toContain("**Install:**");
    expect(result).toContain("codex install example/claude-debugs");
  });

  it("skips install for Bookmark items", () => {
    const result = generateAgentsMd([bookmarkItem]);
    expect(result).not.toContain("**Install:**");
    expect(result).toContain("### Awesome Claude Code");
  });

  it("includes documentation link", () => {
    const result = generateAgentsMd([codexOnlyItem]);
    expect(result).toContain(
      "- [Documentation](https://example.com/codex-tool)"
    );
  });

  it("includes Tool Activation Rules section when items have hints", () => {
    const result = generateAgentsMd([
      {
        ...codexOnlyItem,
        activation_hint: "Run this whenever validating Codex-only workflows.",
      },
    ]);

    expect(result).toContain("## Tool Activation Rules");
    expect(result).toContain("### Codex Tool");
    expect(result).toContain(
      "Run this whenever validating Codex-only workflows."
    );
  });

  it("includes only items with activation hints in Tool Activation Rules", () => {
    const result = generateAgentsMd([
      {
        ...codexOnlyItem,
        activation_hint: "Run this whenever validating Codex-only workflows.",
      },
      { ...skillItem, activation_hint: null },
    ]);

    const activationSection = result.split("## Tool Activation Rules")[1];
    expect(activationSection).toContain("### Codex Tool");
    expect(activationSection).not.toContain("### Claude Debugs For You");
  });

  it("omits Tool Activation Rules section when no items have hints", () => {
    const result = generateAgentsMd([
      { ...codexOnlyItem, activation_hint: null },
      { ...skillItem, activation_hint: null },
    ]);

    expect(result).not.toContain("## Tool Activation Rules");
  });
});
