import { describe, it, expect } from "vitest";
import { generateClaudeMd } from "../claude-md";
import {
  skillItem,
  mcpItem,
  mcpItemWithEnv,
  bookmarkItem,
  allFixtureItems,
} from "./fixtures";

describe("generateClaudeMd", () => {
  it("returns header with attribution", () => {
    const result = generateClaudeMd([]);
    expect(result).toContain("# CLAUDE.md");
    expect(result).toContain("Generated by Tool Bag");
    expect(result).toContain("https://toolbag-sigma.vercel.app");
  });

  it("groups items by category", () => {
    const result = generateClaudeMd(allFixtureItems);
    expect(result).toContain("## Skills & Plugins");
    expect(result).toContain("## MCP Servers");
    expect(result).toContain("## Curated Lists");
  });

  it("includes item name and description", () => {
    const result = generateClaudeMd([skillItem]);
    expect(result).toContain("### Claude Debugs For You");
    expect(result).toContain("Automated debugging skill for Claude Code.");
  });

  it("includes install command for items with claude_code_install", () => {
    const result = generateClaudeMd([skillItem]);
    expect(result).toContain("**Install:**");
    expect(result).toContain("claude install example/claude-debugs");
  });

  it("skips install for Bookmark items", () => {
    const result = generateClaudeMd([bookmarkItem]);
    expect(result).not.toContain("**Install:**");
    expect(result).toContain("### Awesome Claude Code");
  });

  it("includes documentation link", () => {
    const result = generateClaudeMd([skillItem]);
    expect(result).toContain(
      "- [Documentation](https://github.com/example/claude-debugs)"
    );
  });

  it("generates MCP config section for items with mcp_config_claude", () => {
    const result = generateClaudeMd([mcpItem, mcpItemWithEnv]);
    expect(result).toContain("## MCP Servers Configuration");
    expect(result).toContain("`.claude/mcp.json`");
    expect(result).toContain("```json");

    // Validate embedded JSON is parseable
    const jsonMatch = result.match(/```json\n([\s\S]*?)\n```/);
    expect(jsonMatch).not.toBeNull();
    const parsed = JSON.parse(jsonMatch![1]);
    expect(parsed.mcpServers.context7).toBeDefined();
    expect(parsed.mcpServers.context7.command).toBe("npx");
    expect(parsed.mcpServers.supabase).toBeDefined();
    expect(parsed.mcpServers.supabase.env.SUPABASE_ACCESS_TOKEN).toBe(
      "<your-token>"
    );
  });

  it("omits MCP section when no items have mcp_config_claude", () => {
    const result = generateClaudeMd([skillItem, bookmarkItem]);
    expect(result).not.toContain("## MCP Servers Configuration");
  });

  it("includes Tool Activation Rules section when items have hints", () => {
    const result = generateClaudeMd([
      {
        ...skillItem,
        activation_hint: "Use this before debugging complex failures.",
      },
    ]);

    expect(result).toContain("## Tool Activation Rules");
    expect(result).toContain("### Claude Debugs For You");
    expect(result).toContain("Use this before debugging complex failures.");
  });

  it("includes only items with activation hints in Tool Activation Rules", () => {
    const result = generateClaudeMd([
      {
        ...skillItem,
        activation_hint: "Use this before debugging complex failures.",
      },
      { ...mcpItem, activation_hint: null },
    ]);

    const activationSection = result.split("## Tool Activation Rules")[1];
    expect(activationSection).toContain("### Claude Debugs For You");
    expect(activationSection).not.toContain("### Context7 MCP");
  });

  it("omits Tool Activation Rules section when no items have hints", () => {
    const result = generateClaudeMd([
      { ...skillItem, activation_hint: null },
      { ...mcpItem, activation_hint: null },
    ]);

    expect(result).not.toContain("## Tool Activation Rules");
  });
});
