import { describe, it, expect } from "vitest";
import { generateConfigToml } from "../config-toml";
import {
  skillItem,
  mcpItem,
  mcpItemWithEnv,
  allFixtureItems,
} from "./fixtures";

describe("generateConfigToml", () => {
  it("returns header with attribution", () => {
    const result = generateConfigToml([]);
    expect(result).toContain("# Codex config.toml");
    expect(result).toContain("Generated by Tool Bag");
    expect(result).toContain("https://toolbag-sigma.vercel.app");
  });

  it("produces no MCP sections for items without mcp_config", () => {
    const result = generateConfigToml([skillItem]);
    expect(result).not.toContain("[mcp_servers");
    expect(result).not.toContain("# MCP Servers");
  });

  it("generates TOML section headers for MCP items", () => {
    const result = generateConfigToml([mcpItem]);
    expect(result).toContain("# MCP Servers");
    expect(result).toContain("# Context7 MCP");
    expect(result).toContain("[mcp_servers.context7]");
  });

  it("formats string values with quotes", () => {
    const result = generateConfigToml([mcpItem]);
    expect(result).toContain('command = "npx"');
  });

  it("formats array values with brackets", () => {
    const result = generateConfigToml([mcpItem]);
    expect(result).toContain(
      'args = ["-y", "@upstash/context7-mcp@latest"]'
    );
  });

  it("generates env subsection for items with env vars", () => {
    const result = generateConfigToml([mcpItemWithEnv]);
    expect(result).toContain("[mcp_servers.supabase]");
    expect(result).toContain("[mcp_servers.supabase.env]");
    expect(result).toContain('SUPABASE_ACCESS_TOKEN = "<your-token>"');
  });

  it("generates sections for multiple MCP items", () => {
    const result = generateConfigToml([mcpItem, mcpItemWithEnv]);
    expect(result).toContain("[mcp_servers.context7]");
    expect(result).toContain("[mcp_servers.supabase]");
  });

  it("only includes MCP items from mixed input", () => {
    const result = generateConfigToml(allFixtureItems);
    // Should have context7 and supabase sections
    expect(result).toContain("[mcp_servers.context7]");
    expect(result).toContain("[mcp_servers.supabase]");
    // Should not have sections for non-MCP items
    expect(result).not.toContain("[mcp_servers.claude-debugs-for-you]");
    expect(result).not.toContain("[mcp_servers.codex-tool]");
  });
});
