import { groupBy } from "@/lib/utils";
import type { CatalogItem } from "@/types/catalog";

export function generateAgentsMd(items: CatalogItem[]): string {
  const lines: string[] = [];

  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("> Generated by Tool Bag — https://toolbag-sigma.vercel.app");
  lines.push("");

  const grouped = groupBy(items, "category");

  for (const [category, categoryItems] of Object.entries(grouped)) {
    lines.push(`## ${category}`);
    lines.push("");

    for (const item of categoryItems) {
      lines.push(`### ${item.name}`);
      lines.push("");
      lines.push(item.description);
      lines.push("");

      if (
        item.codex_install &&
        item.codex_install !== "Bookmark" &&
        item.codex_install !== "Bookmark (many items cross-compatible)" &&
        item.codex_install !== "Adapt principles to AGENTS.md" &&
        item.codex_install !== "Reference for skill creation" &&
        item.codex_install !== "Visit registry"
      ) {
        lines.push("**Install:**");
        lines.push("```");
        lines.push(item.codex_install);
        lines.push("```");
        lines.push("");
      }

      if (item.url) {
        lines.push(`- [Documentation](${item.url})`);
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}
