import { groupBy } from "@/lib/utils";
import type { CatalogItem } from "@/types/catalog";

export function generateClaudeMd(items: CatalogItem[]): string {
  const lines: string[] = [];

  lines.push("# CLAUDE.md");
  lines.push("");
  lines.push("> Generated by Tool Bag — https://toolbag-sigma.vercel.app");
  lines.push("");

  const grouped = groupBy(items, "category");

  for (const [category, categoryItems] of Object.entries(grouped)) {
    lines.push(`## ${category}`);
    lines.push("");

    for (const item of categoryItems) {
      lines.push(`### ${item.name}`);
      lines.push("");
      lines.push(item.description);
      lines.push("");

      if (
        item.claude_code_install &&
        item.claude_code_install !== "Bookmark" &&
        item.claude_code_install !== "Read and implement" &&
        item.claude_code_install !== "Reference for skill creation"
      ) {
        lines.push("**Install:**");
        lines.push("```");
        lines.push(item.claude_code_install);
        lines.push("```");
        lines.push("");
      }

      if (item.url) {
        lines.push(`- [Documentation](${item.url})`);
        lines.push("");
      }
    }
  }

  // MCP config section
  const mcpItems = items.filter((i) => i.mcp_config_claude);
  if (mcpItems.length > 0) {
    lines.push("## MCP Servers Configuration");
    lines.push("");
    lines.push("Add the following to `.claude/mcp.json`:");
    lines.push("");
    lines.push("```json");
    const merged: Record<string, unknown> = {};
    for (const item of mcpItems) {
      if (item.mcp_config_claude) {
        Object.assign(merged, item.mcp_config_claude);
      }
    }
    lines.push(JSON.stringify({ mcpServers: merged }, null, 2));
    lines.push("```");
    lines.push("");
  }

  // Tool activation rules section
  const itemsWithHints = items.filter((item) => item.activation_hint);
  if (itemsWithHints.length > 0) {
    lines.push("## Tool Activation Rules");
    lines.push("");
    lines.push(
      "These rules tell you WHEN and HOW to use each tool. Follow them proactively."
    );
    lines.push(
      "Do not wait for the user to ask you to use a tool. If a rule applies, use the tool."
    );
    lines.push("");

    for (const item of itemsWithHints) {
      lines.push(`### ${item.name}`);
      lines.push(item.activation_hint!);
      lines.push("");
    }
  }

  return lines.join("\n");
}
