import type { CatalogItem } from "@/types/catalog";

function jsonValueToToml(value: unknown, indent: string = ""): string {
  if (typeof value === "string") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) {
    const items = value.map((v) => jsonValueToToml(v, indent));
    return `[${items.join(", ")}]`;
  }
  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value);
    return entries
      .map(([k, v]) => `${indent}${k} = ${jsonValueToToml(v, indent)}`)
      .join("\n");
  }
  return '""';
}

export function generateConfigToml(items: CatalogItem[]): string {
  const lines: string[] = [];

  lines.push("# Codex config.toml");
  lines.push("# Generated by Codex Catalog — https://codex-catalog.vercel.app");
  lines.push("");

  // MCP server sections from items with mcp_config_claude
  // (adapting Claude MCP configs to TOML format for Codex)
  const mcpItems = items.filter((item) => item.mcp_config_claude !== null);

  if (mcpItems.length > 0) {
    lines.push("# MCP Servers");

    for (const item of mcpItems) {
      if (!item.mcp_config_claude) continue;

      for (const [serverName, config] of Object.entries(
        item.mcp_config_claude
      )) {
        lines.push("");
        lines.push(`# ${item.name}`);
        lines.push(`[mcp_servers.${serverName}]`);

        if (typeof config === "object" && config !== null) {
          const cfg = config as Record<string, unknown>;
          for (const [key, value] of Object.entries(cfg)) {
            if (key === "env" && typeof value === "object" && value !== null) {
              lines.push("");
              lines.push(`[mcp_servers.${serverName}.env]`);
              for (const [envKey, envVal] of Object.entries(value)) {
                lines.push(`${envKey} = ${jsonValueToToml(envVal)}`);
              }
            } else {
              lines.push(`${key} = ${jsonValueToToml(value)}`);
            }
          }
        }
      }
    }
  }

  lines.push("");
  return lines.join("\n");
}
