import type { CatalogItem, McpServerConfig } from "@/types/catalog";

function formatTomlKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key)
    ? key
    : `"${key.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function jsonValueToToml(value: unknown): string {
  if (typeof value === "string") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    return `[${value.map((entry) => jsonValueToToml(entry)).join(", ")}]`;
  }

  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      return "{}";
    }

    return `{ ${entries
      .map(([k, v]) => `${formatTomlKey(k)} = ${jsonValueToToml(v)}`)
      .join(", ")} }`;
  }

  return '""';
}

export function generateConfigToml(items: CatalogItem[]): string {
  const lines: string[] = [];
  const mcpServers = new Map<string, { config: McpServerConfig; source: string }>();

  lines.push("# Codex config.toml");
  lines.push("# Generated by Tool Bag — https://toolbag-sigma.vercel.app");
  lines.push("");

  for (const item of items) {
    const configMap = item.mcp_config_codex ?? item.mcp_config_claude;
    if (!configMap) continue;

    for (const [serverName, serverConfig] of Object.entries(configMap)) {
      mcpServers.set(serverName, {
        config: serverConfig,
        source: item.name,
      });
    }
  }

  if (mcpServers.size > 0) {
    lines.push("# MCP Servers");

    for (const [serverName, { config, source }] of mcpServers.entries()) {
      const serverPath = `mcp.servers.${formatTomlKey(serverName)}`;

      lines.push("");
      lines.push(`# ${source}`);
      lines.push(`[${serverPath}]`);

      for (const [key, value] of Object.entries(config)) {
        if (key === "env" && typeof value === "object" && value !== null) {
          const envEntries = Object.entries(value);
          if (envEntries.length === 0) continue;

          lines.push("");
          lines.push(`[${serverPath}.env]`);
          for (const [envKey, envValue] of envEntries) {
            lines.push(`${formatTomlKey(envKey)} = ${jsonValueToToml(envValue)}`);
          }
          continue;
        }

        lines.push(`${formatTomlKey(key)} = ${jsonValueToToml(value)}`);
      }
    }
  }

  lines.push("");
  return lines.join("\n");
}
